# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 4.0

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
